### ISSUE TITLE
Bump and publish on NPM

### ISSUE THREAD

**Issue by SamyPesse** [coolaj86/isbnjs#8]
Latest version on NPM is not working for node, but fixed on github: https://github.com/coolaj86/isbnjs/commit/138750331a133300fcba629f21522e114bf8411c

**Comment by taitems** [comment]
Bump. Implementing the above closes Issue #9 too.

**Comment by coolaj86** [comment]
Give me your npm username and I will add you.

**Comment by taitems** [comment]
Just joined here https://www.npmjs.com/~taitems

**Comment by coolaj86** [comment]
Thanks. You now have write access. :-)

**Comment by taitems** [comment]
@SamyPesse @coolaj86 This should be resolved. I bumped the version in `package.json` to enable the `npm publish` to successfully run. Working for me now with an `npm install` in another project so I'm marking this as closed.
